### ISSUE TITLE
2FA not working for OpenVPN

### ISSUE THREAD

**Issue by f-helm** [passepartoutvpn/passepartout-apple#256] opened 2023-02-16 17:38 UTC
Since I didn't find clues whether or not 2FA in a extra prompt with OpenVPN is supported, I assumed it is.
Issue https://github.com/passepartoutvpn/passepartout-apple/issues/3 already exists, but is a different case.

After importing my ovpn profile and entering user and password, I toggle `Enabled` to `On`. I would expect a prompt to enter the OTP, but nothing happens, status changes to `Connecting` and stays in it, nothing happens.

ovpn profile contains these lines:
```
auth-user-pass
static-challenge "Enter Authenticator Code" 1
```

Works with other OpenVPN clients without issue.
Version is 2.0.2 (3395) on macOS 13.1

**Comment by keeshux** [comment] 2023-02-23 21:28
`static-challenge` is not a supported option. Why wouldn't this be a duplicate of #3?

**Closed** 2023-03-03 06:34 UTC
