### ISSUE TITLE
[Feature request] Add OTP Field in Account section

### ISSUE THREAD

**Issue by F3000** [passepartoutvpn/passepartout-apple#255] opened 2023-01-04 23:36 UTC
E.g. I use following password scheme for my work VPN 

user: username
Password: passwordOTP

This new field can be activated through a checkbox . 

It would be useful when the app generates the OTP code

**Comment by keeshux** [comment] 2023-01-05 15:11
Kind of duplicate of #3

**Closed by keeshux** 2023-01-05 15:11 UTC
