### ISSUE TITLE
Suggestion: Add an option to disable VPN for X minutes

### ISSUE THREAD

**Issue by bolducd** [passepartoutvpn/passepartout-apple#198] opened 2021-10-30 11:40 UTC
Sometimes I need to disable VPN for a few minutes to configure wifi iot devices and a VPN can cause problems while doing this so I disable VPN on my iphone while doing it but I frequently forget to enable the VPN after. 

I suggest an option like pi-hole. When you disable you have a popup asking if you would like to disable only for x minutes. 

Thanks

**Comment by keeshux** [comment] 2021-11-05 10:27
Duplicate of https://github.com/passepartoutvpn/passepartout-apple/issues/185

**Closed by keeshux** 2021-11-05 10:27 UTC
