### ISSUE TITLE
Keep alive on sleep not working on iphone 16.4.1

### ISSUE THREAD

**Issue by dmitrydonskih** [passepartoutvpn/passepartout-apple#299] opened 2023-05-21 22:47 UTC
Hello. I am using Passepartout 2.1.1 (3468) on IPhone iOS 16.4.1.
I connect to my OpenVPN server, then leave iphone, it goes sleep, and after 1-2 minutes VPN is disconnected (as of server-side logs).
An option to keep connection alive is enabled in VPN profile.

In iphone VPN log:
```
01:10:56 - Send ping
01:11:05 - Data: Received ping, do nothing
01:11:07 - Send ping
01:11:15 - Data: Received ping, do nothing
01:11:18 - Send ping
01:12:15 - Data: Received ping, do nothing
01:12:22 - Send ping
01:12:25 - Data: Received ping, do nothing
01:17:22 - Trigger shutdown (error: pingTimeout)
```
See the gap between 01:12 and 01:17 - at 01:11 iphone has gone sleeping, at 01:13 server said "client gone", at 01:17 I woke it up.

More things worth mentioning:
This is not wifi/cellular connectivity issue - iphone still receives messages and calls when sleeping.
Wifi "traffic economy" setting is off. Energy saving is off. VPN "on demand" iOS setting for this profile is off.
Both OpenVPN server and client have enabled keepalive setting.
Client VPN profile does **not** use default gateway nor DNS from VPN server - it is set up only for SIP PBX.

[debug-vpn.txt](https://github.com/passepartoutvpn/passepartout-apple/files/11525686/debug-vpn.txt)

**Comment by keeshux** [comment] 2023-05-22 07:35
Duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/138

**Closed by keeshux** 2023-05-22 07:35 UTC
